### ISSUE TITLE
Unrecognised format with Nabu Casa

### ISSUE THREAD

**Issue by nlindblo** [nimroddolev/chime_tts#23]
## System Information

version | core-2023.9.2
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 5.10.0-23-amd64
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1299
Downloaded Repositories | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 27 October 2023 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 21
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 26 September 2023 at 06:40
-- | --
current_recorder_run | 26 September 2023 at 20:47
estimated_db_size | 611.00 MiB
database_engine | mysql
database_version | 11.1.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I installed this plugin via HACS and cannot get the chime to work, the debug logs looks like there is incompatibility with the file format and that the speech is not returned from Nabu Casa causing a 404. I am running HA in Kubernetes (i.e. docker container) and using tts from Nabu Casa, which works.

Please see debug log for details

### Reproduction steps

```
alias: Apartment Doorbell Ring
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 2f2b67f724a6bdd6c301aa1c95e57b3e
    type: action
    subtype: pressed
    discovery_id: 0x5c0272fffee7c4c7 action_pressed
condition: []
action:
  - service: chime_tts.say
    data:
      end_chime_path: custom_components/chime_tts/mp3s/chirp.mp3
      delay: 450
      final_delay: 0
      tts_playback_speed: 100
      volume_level: 0.5
      message: Theres someone at the door
      tts_platform: cloud
      chime_path: custom_components/chime_tts/mp3s/bells_2.mp3
    target:
      entity_id: media_player.homepod_office
mode: single
```

### Debug logs

```text
2023-09-27 08:04:41.974 INFO (MainThread) [homeassistant.components.automation.apartment_doorbell_ring] Apartment Doorbell Ring: Executing step call service
2023-09-27 08:04:44.203 ERROR (MainThread) [root] Failed to parse metadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyatv/protocols/raop/audio_source.py", line 263, in get_buffered_io_metadata
    return await get_metadata(buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyatv/support/metadata.py", line 25, in get_metadata
    in_file = await loop.run_in_executor(None, _open_file, file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyatv/support/metadata.py", line 15, in _open_file
    in_file = MediaFile(file)
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mediafile.py", line 165, in wrapper
    return mutagen_call('loadfile', '', f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mediafile.py", line 137, in mutagen_call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mutagen/_util.py", line 155, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mediafile.py", line 1586, in __init__
    raise FileTypeError(self.filename)
mediafile.FileTypeError: 'https://ogift7s3cbaedvngj0m5til283tegh8j.ui.nabu.casa/media/local/sounds/temp/chime_tts/jw5dmpx0.mp3?authSig=<REDACTE>?': not in a recognized format
2023-09-27 08:04:44.213 WARNING (MainThread) [custom_components.chime_tts] An unexpected error occurred: Got status 404 with message: Not Found
```

**Comment by nimroddolev** [comment]
Hi @nlindblo,

Sorry to hear you're having an issue with the TTS audio. It would be helpful if you could turn on debug logging for the integration so that I can get a clearer idea of what's going on:

1. Turn on debug logging:
```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

2. Call the service chime_tts.say again.

3. Check your log messages in Home Assistant:
```
https://{YOUR_HOME_ASSISTANT_ADDRESS}:8123/config/logs?filter=chime_tts
```
and click `LOAD FULL LOGS`

**Comment by nlindblo** [comment]
Here you go

```
2023-09-27 09:14:52.473 DEBUG (MainThread) [custom_components.chime_tts] Executing queued job #0
2023-09-27 09:14:52.473 DEBUG (MainThread) [custom_components.chime_tts] ----- Chime TTS Say Called -----
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * entity_ids = ['media_player.homepod_office_room']
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * hass = <homeassistant.core.HomeAssistant object at 0x7f8c31e7a850>
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * chime_path = custom_components/chime_tts/mp3s/bells_2.mp3
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * end_chime_path = custom_components/chime_tts/mp3s/chirp.mp3
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * delay = 450.0
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * message = Theres someone at the door
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * tts_platform = cloud
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * tts_playback_speed = 100.0
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * volume_level = 0.5
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * join_players = False
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * cache = False
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] * announce = False
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] ------
2023-09-27 09:14:52.474 DEBUG (MainThread) [custom_components.chime_tts] async_get_playback_audio_path
2023-09-27 09:14:52.475 DEBUG (MainThread) [custom_components.chime_tts] get_audio_from_path("custom_components/chime_tts/mp3s/bells_2.mp3", 0, audio)
2023-09-27 09:14:52.475 DEBUG (MainThread) [custom_components.chime_tts] - Retrieving audio from path: "custom_components/chime_tts/mp3s/bells_2.mp3"...
2023-09-27 09:14:52.568 DEBUG (MainThread) [custom_components.chime_tts] - ...audio with duration 1.279s retrieved successfully
2023-09-27 09:14:52.568 DEBUG (MainThread) [custom_components.chime_tts] async_request_tts_audio(hass, tts_platform="cloud", message="Theres someone at the door", cache="False", language="None", tld="None", gender="None", tts_playback_speed="100.0"))
2023-09-27 09:14:52.568 DEBUG (MainThread) [custom_components.chime_tts] - Generating TTS audio...
2023-09-27 09:14:53.330 DEBUG (MainThread) [custom_components.chime_tts] - ...TTS audio completed in 761.809 ms
2023-09-27 09:14:53.333 DEBUG (MainThread) [custom_components.chime_tts] get_audio_from_path("custom_components/chime_tts/mp3s/chirp.mp3", 450.0, audio)
2023-09-27 09:14:53.333 DEBUG (MainThread) [custom_components.chime_tts] - Retrieving audio from path: "custom_components/chime_tts/mp3s/chirp.mp3"...
2023-09-27 09:14:53.408 DEBUG (MainThread) [custom_components.chime_tts] - ...audio with duration 0.395s retrieved successfully
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - Final audio created:
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - Duration = 5.022s
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] Creating final audio file
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - Temp folder exists: /media/sounds/temp/chime_tts/
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - Creating temporary mp3 file...
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - temp_obj = <tempfile._TemporaryFileWrapper object at 0x7f8c041d76d0>
2023-09-27 09:14:53.409 DEBUG (MainThread) [custom_components.chime_tts] - Filepath = '/media/sounds/temp/chime_tts/q3tr0u21.mp3'
2023-09-27 09:14:53.506 DEBUG (MainThread) [custom_components.chime_tts] - File saved successfully
2023-09-27 09:14:53.506 DEBUG (MainThread) [custom_components.chime_tts] - audio_dict = {'audio_path': '/media/sounds/temp/chime_tts/q3tr0u21.mp3', 'audio_duration': 5.022}
2023-09-27 09:14:53.506 DEBUG (MainThread) [custom_components.chime_tts] - Setting 'media_player.homepod_office_room' volume level to 0.5
2023-09-27 09:14:53.506 DEBUG (MainThread) [custom_components.chime_tts] - async_set_volume_level("media_player.homepod_office_room", 0.5)
2023-09-27 09:14:53.506 DEBUG (MainThread) [custom_components.chime_tts] - Seting volume_level of media player "media_player.homepod_office_room" to: 0.5
2023-09-27 09:14:53.710 DEBUG (MainThread) [custom_components.chime_tts] - Volume set
2023-09-27 09:14:53.710 DEBUG (MainThread) [custom_components.chime_tts] Calling media_player.play_media service with data:
2023-09-27 09:14:53.710 DEBUG (MainThread) [custom_components.chime_tts] - media_content_type: music
2023-09-27 09:14:53.711 DEBUG (MainThread) [custom_components.chime_tts] - media_content_id: media-source://media_source/local/sounds/temp/chime_tts/q3tr0u21.mp3
2023-09-27 09:14:53.711 DEBUG (MainThread) [custom_components.chime_tts] - entity_id: ['media_player.homepod_office']
mediafile.FileTypeError: 'https://ogift7s3cbaedvngj0m5til283tegh8j.ui.nabu.casa/media/local/sounds/temp/chime_tts/q3tr0u21.mp3?authSig=<REDACTED>': not in a recognized format
2023-09-27 09:14:54.966 WARNING (MainThread) [custom_components.chime_tts] An unexpected error occurred: Got status 404 with message: Not Found
2023-09-27 09:14:54.969 DEBUG (MainThread) [custom_components.chime_tts] Waiting 5.022s for audio playback to complete...
2023-09-27 09:14:59.992 DEBUG (MainThread) [custom_components.chime_tts] Returning media_player.homepod_office_room's volume level to 0.264
2023-09-27 09:14:59.992 DEBUG (MainThread) [custom_components.chime_tts] - async_set_volume_level("media_player.homepod_office_room", 0.264)
2023-09-27 09:14:59.993 DEBUG (MainThread) [custom_components.chime_tts] - Seting volume_level of media player "media_player.homepod_office_room" to: 0.264
2023-09-27 09:15:00.059 DEBUG (MainThread) [custom_components.chime_tts] - Volume set
2023-09-27 09:15:00.059 DEBUG (MainThread) [custom_components.chime_tts] ----- Chime TTS Say Completed in 7585.525 ms -----
2023-09-27 09:15:00.059 DEBUG (MainThread) [custom_components.chime_tts] Removing current queued service call.
2023-09-27 09:15:00.059 DEBUG (MainThread) [custom_components.chime_tts] Queue emptied. Reinitializing values.
```

**Comment by nimroddolev** [comment]
Based on your debug log messages it looks like Chime TTS successfully retrieves the audio from the 'chime' mp3 files and TTS audio, and also succeeds in generating a temp mp3 file for playback.

The issue occurs when trying to play the temp mp3 file via 'media_player.play_media`:

```
2023-09-27 09:14:53.710 DEBUG (MainThread) [custom_components.chime_tts] Calling media_player.play_media service with data:
2023-09-27 09:14:53.710 DEBUG (MainThread) [custom_components.chime_tts] - media_content_type: music
2023-09-27 09:14:53.711 DEBUG (MainThread) [custom_components.chime_tts] - media_content_id: media-source://media_source/local/sounds/temp/chime_tts/q3tr0u21.mp3
2023-09-27 09:14:53.711 DEBUG (MainThread) [custom_components.chime_tts] - entity_id: ['media_player.homepod_office']
mediafile.FileTypeError: 'https://ogift7s3cbaedvngj0m5til283tegh8j.ui.nabu.casa/media/local/sounds/temp/chime_tts/q3tr0u21.mp3?authSig=<REDACTED>': not in a recognized format
```

The `media_content_id` source looks correct but perhaps your Home Assistant instance doesn't have access to the media folder.

Can you please try adding the following YAML to your `configurations.yaml` file, restart, and try calling `chime_tts.say` again?

```
homeassistant:
  media_dirs:
    local: /media
```

**Comment by nimroddolev** [comment]
Happy to hear it! 👍
