### ISSUE TITLE
Error attempting to Configure Chime_TTS

### ISSUE THREAD

**Issue by DanfieldNet** [nimroddolev/chime_tts#230]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1497
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2025 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
instance_id | 16998a41d9224c818c351f3349a01f9b
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 62.3 GB
disk_used | 13.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.16.0), File editor (5.8.0), Studio Code Server (5.17.3), Z-Wave JS UI (3.18.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.3.2), Portainer (2.24.1), Mosquitto broker (6.4.1), Zigbee2MQTT (1.42.0-2), NGINX Home Assistant SSL proxy (3.11.1), Piper (1.5.2), ESPHome Device Compiler (2024.11.3), Ring-MQTT with Video Streaming (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 6
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 7, 2024 at 4:32 PM
-- | --
current_recorder_run | December 15, 2024 at 6:36 PM
estimated_db_size | 611.08 MiB
database_engine | sqlite
database_version | 3.45.3

</details>
![2024-12-15_18-40-49](https://github.com/user-attachments/assets/4db0d7fb-9aeb-435b-bdd3-9269e240c8e2)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After updating to version v1.2.0 I am attempting to Configure and getting 500 Internal Server Error (screenshot attached).

### Reproduction steps

1. Go to Integrations
2. Click Chime-TTS
3. Click Configure
...

### Debug logs

```text
2024-12-15 18:47:27.768 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.769 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration variable which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.770 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.771 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homeseer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.772 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.772 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.773 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.774 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.774 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ge_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.775 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.776 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration multiscrape which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.776 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration chime_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.777 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration battery_notes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:27.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 18:47:29.571 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2024-12-15 18:47:33.079 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'o365' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry and will stop working in Home Assistant 2025.11 at custom_components/o365/helpers/setup.py, line 73: await email_coordinator.async_config_entry_first_refresh(), please create a bug report at https://github.com/RogerSelwyn/O365-HomeAssistant/issues
2024-12-15 18:47:33.275 WARNING (ImportExecutor_0) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2024-12-15 18:47:33.547 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f71c8d0e650>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by integration 'harmony' at homeassistant/components/harmony/data.py, line 118: connected = await self._client.connect() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+harmony%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/harmony/__init__.py", line 28, in async_setup_entry
    await data.connect()
  File "/usr/src/homeassistant/homeassistant/components/harmony/data.py", line 118, in connect
    connected = await self._client.connect()

2024-12-15 18:47:34.346 WARNING (SyncWorker_32) [hyundai_kia_connect_api.HyundaiBlueLinkApiUSA] hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'IDM_PIN_607', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Your pin has been locked permanently, please input security questions and answers to update the pin.', 'errorMessage': 'Your pin has been locked permanently, please contact the call center.', 'errorCode': 401, 'serviceName': 'CheckCustomerUserPin'}
2024-12-15 18:47:38.024 WARNING (MainThread) [homeassistant.components.vesync.fan] Humidifier - Unknown device type - Classic300S
2024-12-15 18:47:43.453 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32devkitv1 @ 192.168.1.100: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.100', port=6053))]: [Errno 113] Connect call failed ('192.168.1.100', 6053) (SocketAPIError)
2024-12-15 18:47:44.246 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID notification_alexa_command_remote already exists - ignoring automation.notification_alexa_command_remote
2024-12-15 18:47:44.247 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID notification_power_ups_monitor_change already exists - ignoring automation.notification_power_ups_monitor_change
2024-12-15 18:47:44.254 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID notification_add-on_monitoring already exists - ignoring automation.notification_add_on_monitoring
2024-12-15 18:47:44.992 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_MUSIC was used from hass_agent, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'hass_agent' custom integration
2024-12-15 18:47:49.960 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hass_agent' calls media_source.async_resolve_media without passing an entity_id at custom_components/hass_agent/media_player.py, line 301: play_item = await media_source.async_resolve_media(self.hass, media_id), please create a bug report at https://github.com/hass-agent/HASS.Agent-Integration/issues
2024-12-15 18:47:54.152 ERROR (MainThread) [custom_components.multiscrape.sensor] MultiScrape TwinBridges # MultiScrape Twin Bridges Notification # Unable to scrape data: Could not find a tag for given selector 
Consider using debug logging and log_response for further investigation.
2024-12-15 18:47:54.156 ERROR (MainThread) [custom_components.multiscrape.entity] MultiScrape TwinBridges # MultiScrape Twin Bridges Notification # full_text # Unable to extract data from HTML
2024-12-15 18:48:08.394 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╔════════════════════════════════════════╗
2024-12-15 18:48:08.394 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ║ Chime TTS Version v1.2.0 Configuration ║
2024-12-15 18:48:08.394 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╚════════════════════════════════════════╝
2024-12-15 18:48:08.395 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 342, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chime_tts/config_flow.py", line 102, in async_step_init
    QUEUE_TIMEOUT_KEY: self.get_data_key_value(QUEUE_TIMEOUT_KEY, user_input, QUEUE_TIMEOUT_DEFAULT),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chime_tts/config_flow.py", line 271, in get_data_key_value
    dicts = [dict(self.config_entry.options), dict(self.config_entry.data)]
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'ChimeTTSOptionsFlowHandler' object has no attribute 'config_entry'
```

**Comment by nimroddolev** [comment]
Thank you, I will add a fix in the next release

**Comment by DanfieldNet** [comment]
This is now working, thank you.  However, I'm not getting the fallback TTS working.  I will open a separate Issue
