### ISSUE TITLE
Fallback TTS not working

### ISSUE THREAD

**Issue by DanfieldNet** [nimroddolev/chime_tts#232]
## System Information

version | core-2024.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2025 at 7:00 PM
relayer_connected | false
relayer_region | us-east-1
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
instance_id | 16998a41d9224c818c351f3349a01f9b
can_reach_cert_server | pending
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 62.3 GB
disk_used | 13.6 GB
healthy | true
supported | true
host_connectivity | false
supervisor_connectivity | false
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | pending
installed_addons | Terminal & SSH (9.16.0), File editor (5.8.0), Studio Code Server (5.17.3), Z-Wave JS UI (3.18.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.3.2), Portainer (2.24.1), Mosquitto broker (6.4.1), Zigbee2MQTT (1.42.0-2), NGINX Home Assistant SSL proxy (3.11.1), Piper (1.5.2), ESPHome Device Compiler (2024.11.3), Ring-MQTT with Video Streaming (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 6
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 7, 2024 at 4:32 PM
-- | --
current_recorder_run | December 16, 2024 at 12:37 PM
estimated_db_size | 611.08 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have configured Piper as the Fallback TTS in the Chime Configuration (cloud is the default); however, it is not working.  I simulated an Internet connection outage (via firewall rule) and attempted to have Chime fall back to Piper if it could not reach NabuCasa (cloud), but received timeout error.

action: chime_tts.say
data:
  chime_path: custom_components/chime_tts/mp3s/bells.mp3
  message: This is a test
  tts_platform: cloud
target:
  entity_id: media_player.hass_agent_nas

 Confirmed both cloud and piper are working correctly with Chime via Dev Tools when selected as tts_platform.

### Reproduction steps

1. Configure Chime_TTS with fallback TTS of piper via dropdown in Configuration options (cloud is the default TTS)
2. Simulate Internet outage via firewall rule
3. Attempt chime_tts.say via Development Tools
4. Received timeout error (does not fallback(
...

### Debug logs

```text
2024-12-16 12:37:20.644 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.645 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration variable which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.645 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.646 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homeseer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.648 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.648 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.649 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.650 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.651 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ge_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.651 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.652 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration multiscrape which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.652 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration chime_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.653 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration battery_notes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:20.654 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 12:37:22.605 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2024-12-16 12:37:27.770 WARNING (ImportExecutor_0) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2024-12-16 12:37:28.997 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'o365' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry at custom_components/o365/helpers/setup.py, line 73: await email_coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/RogerSelwyn/O365-HomeAssistant/issues
2024-12-16 12:37:31.342 WARNING (SyncWorker_0) [hyundai_kia_connect_api.HyundaiBlueLinkApiUSA] hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'IDM_PIN_607', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Your pin has been locked permanently, please input security questions and answers to update the pin.', 'errorMessage': 'Your pin has been locked permanently, please contact the call center.', 'errorCode': 401, 'serviceName': 'CheckCustomerUserPin'}
2024-12-16 12:37:33.127 WARNING (MainThread) [homeassistant.components.vesync.fan] Humidifier - Unknown device type - Classic300S
2024-12-16 12:37:38.773 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32devkitv1 @ 192.168.1.100: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.100', port=6053))]: [Errno 113] Connect call failed ('192.168.1.100', 6053) (SocketAPIError)
2024-12-16 12:37:40.426 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_MUSIC was used from hass_agent, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'hass_agent' custom integration
2024-12-16 12:37:47.371 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hass_agent' calls media_source.async_resolve_media without passing an entity_id at custom_components/hass_agent/media_player.py, line 301: play_item = await media_source.async_resolve_media(self.hass, media_id). Please create a bug report at https://github.com/hass-agent/HASS.Agent-Integration/issues
2024-12-16 12:37:51.103 ERROR (MainThread) [custom_components.multiscrape.sensor] MultiScrape TwinBridges # MultiScrape Twin Bridges Notification # Unable to scrape data: Could not find a tag for given selector 
Consider using debug logging and log_response for further investigation.
2024-12-16 12:37:51.107 ERROR (MainThread) [custom_components.multiscrape.entity] MultiScrape TwinBridges # MultiScrape Twin Bridges Notification # full_text # Unable to extract data from HTML
2024-12-16 12:38:26.399 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╔══════════════════════════════════════╗
2024-12-16 12:38:26.399 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ║ Chime TTS Say Called. Version v1.2.1 ║
2024-12-16 12:38:26.399 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╚══════════════════════════════════════╝
2024-12-16 12:38:26.399 DEBUG (MainThread) [custom_components.chime_tts.queue_manager] Adding service call to queue
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╭────────────────────╮
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] │ General Parameters │
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╰────────────────────╯
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * entity_ids = ['media_player.hass_agent_nas']
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * chime_path = custom_components/chime_tts/mp3s/bells.mp3
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * cache = False
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * offset = 450.0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * crossfade = 0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * final_delay = 0.0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * message = This is a test
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * tts_platform = cloud
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * tts_speed = 100.0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * tts_pitch = 0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * announce = False
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * fade_audio = False
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * volume_level = -1
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * join_players = False
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * unjoin_players = False
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]  * media_players_array:
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]    - 0: entity_id: media_player.hass_agent_nas
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      platform: hass_agent
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      initial volume: 0.0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      target volume: -1.0
2024-12-16 12:38:26.400 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      now playing: False
2024-12-16 12:38:26.401 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      join supported: False
2024-12-16 12:38:26.401 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers]      announce supported: False
2024-12-16 12:38:26.401 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╭─────────────────╮
2024-12-16 12:38:26.401 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] │ Preparing Audio │
2024-12-16 12:38:26.401 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] ╰─────────────────╯
2024-12-16 12:38:26.407 DEBUG (MainThread) [custom_components.chime_tts]  - Retrieving audio from path: "custom_components/chime_tts/mp3s/bells.mp3"...
2024-12-16 12:38:26.532 DEBUG (MainThread) [custom_components.chime_tts]    ...audio retrieved. Duration: 0.944s
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]  - Generating new TTS audio with parameters:
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]     * tts_platform = 'cloud'
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]     * message = 'This is a test'
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]     * cache = False
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]     * language = None
2024-12-16 12:38:26.534 DEBUG (MainThread) [custom_components.chime_tts]     * options = {}
2024-12-16 12:38:42.687 ERROR (MainThread) [homeassistant.components.meater] Timeout fetching meater_api data
2024-12-16 12:38:43.501 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.air_purifier_family_room is taking over 10 seconds
2024-12-16 12:38:59.516 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.air_purifier_bedroom is taking over 10 seconds
2024-12-16 12:39:03.501 WARNING (MainThread) [homeassistant.components.fan] Updating vesync fan took longer than the scheduled update interval 0:00:30
2024-12-16 12:39:26.400 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback SpeechManager._async_get_tts_audio.<locals>.handle_error() at /usr/src/homeassistant/homeassistant/components/tts/__init__.py:844 (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 846, in handle_error
    if audio_task.exception():
       ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 782, in get_tts_data
    extension, data = await engine_instance.async_get_tts_audio(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message, language, options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/cloud/tts.py", line 284, in async_get_tts_audio
    data = await self.cloud.voice.process_tts(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/voice.py", line 1323, in process_tts
    await self._update_token()
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/voice.py", line 1237, in _update_token
    resp = await cloud_api.async_voice_connection_details(self.cloud)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/cloud_api.py", line 75, in check_token
    return await func(cloud, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/cloud_api.py", line 91, in log_response
    resp = await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/cloud_api.py", line 194, in async_voice_connection_details
    return await cloud.websession.get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
        current_loop, exceptions, addrinfo, local_addr_infos
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError
2024-12-16 12:39:26.516 WARNING (MainThread) [custom_components.chime_tts.queue_manager] Service call {'function': <function async_setup.<locals>.async_say_execute at 0x7f17fc1e1260>, 'args': (<ServiceCall chime_tts.say (c:01JF88SGYY4M8TKE031RRCQG18): chime_path=custom_components/chime_tts/mp3s/bells.mp3, message=This is a test, tts_platform=cloud, entity_id=['media_player.hass_agent_nas']>, False), 'kwargs': {}, 'future': <Future pending cb=[Task.task_wakeup()]>} timed out after 60.12s
2024-12-16 12:39:26.517 ERROR (MainThread) [custom_components.chime_tts] Error calling chime_tts.say service: Service call timed out after 60.12s (configured timeout = 60s)
2024-12-16 12:39:26.518 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Service call timed out after 60.12s (configured timeout = 60s)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chime_tts/__init__.py", line 141, in async_say
    result = await queue.add_to_queue(async_say_execute, timeout, service, is_say_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: Service call timed out after 60.12s (configured timeout = 60s)
2024-12-16 12:39:26.522 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139740691783184] Error handling message: Timeout (timeout) William Cross from 192.168.1.32 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
2024-12-16 12:39:29.207 WARNING (MainThread) [hass_nabucasa.google_report_state] Unable to connect: Connection timeout to host wss://remotestate.nabucasa.com/v1
2024-12-16 12:39:35.224 ERROR (MainThread) [gehomesdk.clients.websocket_client] Unknown error reading socket
```

**Comment by DanfieldNet** [comment]
![2024-12-16_17-23-17](https://github.com/user-attachments/assets/80a2764b-366d-4913-a77a-eaf030f3d311)

**Comment by DanfieldNet** [comment]
![2024-12-16_17-26-59](https://github.com/user-attachments/assets/e5537bfc-df67-4a88-8ef9-299ae6041951)

**Comment by nimroddolev** [comment]
Hi @DanfieldNet. Thanks for opening the issue.

I have a fix and have released a new beta version, v1.2.2-beta1.
Could you please [install it](https://nimroddolev.github.io/chime_tts/docs/quick-start/installing-chime-tts#beta-versions) and let me know if the issue is now resolved for you?

**Comment by DanfieldNet** [comment]
I'm sorry, no it didn't work.  Still received "Failed to perform the action chime_tts.say. Timeout" error
[home-assistant_chime_tts_2024-12-18T04-56-16.454Z.log](https://github.com/user-attachments/files/18175251/home-assistant_chime_tts_2024-12-18T04-56-16.454Z.log)

**Comment by nimroddolev** [comment]
Could you please test the new beta version, v1.2.2-beta3, and let me know if the issue is resolved?

**Comment by DanfieldNet** [comment]
Sorry, still no.  Debug log below.
[home-assistant_chime_tts_2024-12-26T19-46-23.329Z.log](https://github.com/user-attachments/files/18255161/home-assistant_chime_tts_2024-12-26T19-46-23.329Z.log)

**Comment by nimroddolev** [comment]
This issue has been addressed in the **v1.3.0-beta1** release. Please [install the beta](https://nimroddolev.github.io/chime_tts/docs/quick-start/installing-chime-tts#beta-versions) and let me know.
